#include <stdint.h>

#define ACTR "rtca"
#define ACTV "vtca"
#define ANT "!tna"
#define ANTR "rtna"
#define BIPD "dpib"
#define BITM "mtib"
#define BOOM "moob"
#define CDMG "gmdc"
#define COLL "lloc"
#define COLO "oloc"
#define CONT "tnoc"
#define CTRL "lrtc"
#define DECA "aced"
#define DELA "aLeD"
#define DEVC "cved"
#define DEVI "ived"
#define DOBC "cbod"
#define EFFE "effe"
#define ELEC "cele"
#define EQIP "piqe"
#define FLAG "galf"
#define FOG  " gof"
#define FONT "tnof"
#define FOOT "toof"
#define GARB "brag"
#define GLW "!wlg"
#define GRHI "ihrg"
#define HMT  " tmh"
#define HUD "#duh"
#define HUDG "gduh"
#define ITEM "meti"
#define ITMC "cmti"
#define JPT "!tpj"
#define LENS "snel"
#define LIFI "ifil"
#define LIGH "hgil"
#define LSND "dnsl"
#define MACH "hcam"
#define MATG "gtam"
#define METR "rtem"
#define MGS2 "2sgm"
#define MOD2 "2dom"
#define MODE "edom"
#define MPLY "ylpm"
#define NGPR "rpgn"
#define OBJE "ejbo"
#define PART "trap"
#define PCTL "ltcp"
#define PHYS "syhp"
#define PLAC "calp"
#define PPHY "yhpp"
#define PROJ "jorp"
#define RAIN "niar"
#define SBSP "psbs"
#define SCEN "necs"
#define SCEX "xecs"
#define SCHI "ihcs"
#define SCNR "rncs"
#define SENV "vnes"
#define SGLA "algs"
#define SHDR "rdhs"
#define SKY  " yks"
#define SMET "tems"
#define SND "!dns"
#define SNDE "edns"
#define SOSO "osos"
#define SOTR "rtos"
#define SOUL "luoS"
#define SPLA "alps"
#define SSCE "ecss"
#define STR "#rts"
#define SWAT "taws"
#define TAGC "cgat"
#define TRAK "kart"
#define UDLG "gldu"
#define UNHI "ihnu"
#define UNIT "tinu"
#define USTR "rtsu"
#define VCKY "ykcv"
#define VEHI "ihev"
#define WEAP "paew"
#define WIND "dniw"
#define WPHI "ihpw"

#ifndef deathstar_ZZTTagClasses_h
#define deathstar_ZZTTagClasses_h
const char *translateHaloClassToName(uint32_t className);
#endif
