#include <stdio.h>
#include "ZZTTagClasses.h"

const char *translateHaloClassToName(uint32_t className) { //from Halo Editing Kit
    if(className == *(uint32_t *)&ACTR) return "actor";
    else if(className == *(uint32_t *)&ACTV) return "actor_variant";
    else if(className == *(uint32_t *)&ANT) return "antenna";
    else if(className == *(uint32_t *)&ANTR) return "model_animations";
    else if(className == *(uint32_t *)&BIPD) return "biped";
    else if(className == *(uint32_t *)&BITM) return "bitmap";
    else if(className == *(uint32_t *)&BOOM) return "spheroid";
    else if(className == *(uint32_t *)&CDMG) return "continuous_damage_effect";
    else if(className == *(uint32_t *)&COLL) return "model_collision_geometry";
    else if(className == *(uint32_t *)&COLO) return "color_table";
    else if(className == *(uint32_t *)&CONT) return "contrail";
    else if(className == *(uint32_t *)&CTRL) return "device_control";
    else if(className == *(uint32_t *)&DECA) return "decal";
    else if(className == *(uint32_t *)&DELA) return "ui_widget_definition";
    else if(className == *(uint32_t *)&DEVC) return "input_device_defaults";
    else if(className == *(uint32_t *)&DEVI) return "device";
    else if(className == *(uint32_t *)&DOBC) return "detail_object_collection";
    else if(className == *(uint32_t *)&EFFE) return "effect";
    else if(className == *(uint32_t *)&ELEC) return "lightning";
    else if(className == *(uint32_t *)&EQIP) return "equipment";
    else if(className == *(uint32_t *)&FLAG) return "flag";
    else if(className == *(uint32_t *)&FOG ) return "fog";
    else if(className == *(uint32_t *)&FONT) return "font";
    else if(className == *(uint32_t *)&FOOT) return "material_effects";
    else if(className == *(uint32_t *)&GARB) return "garbage";
    else if(className == *(uint32_t *)&GLW) return "glow";
    else if(className == *(uint32_t *)&GRHI) return "grenade_hud_interface";
    else if(className == *(uint32_t *)&HMT ) return "hud_message_text";
    else if(className == *(uint32_t *)&HUD) return "hud_number";
    else if(className == *(uint32_t *)&HUDG) return "hud_globals";
    else if(className == *(uint32_t *)&ITEM) return "item";
    else if(className == *(uint32_t *)&ITMC) return "item_collection";
    else if(className == *(uint32_t *)&JPT) return "damage_effect";
    else if(className == *(uint32_t *)&LENS) return "lens_flare";
    else if(className == *(uint32_t *)&LIFI) return "device_light_fixture";
    else if(className == *(uint32_t *)&LIGH) return "light";
    else if(className == *(uint32_t *)&LSND) return "sound_looping";
    else if(className == *(uint32_t *)&MACH) return "device_machine";
    else if(className == *(uint32_t *)&MATG) return "globals";
    else if(className == *(uint32_t *)&METR) return "meter";
    else if(className == *(uint32_t *)&MGS2) return "light_volume";
    else if(className == *(uint32_t *)&MOD2) return "gbxmodel";
    else if(className == *(uint32_t *)&MODE) return "model";
    else if(className == *(uint32_t *)&MPLY) return "multiplayer_scenario_description";
    else if(className == *(uint32_t *)&NGPR) return "preferences_network_game";
    else if(className == *(uint32_t *)&OBJE) return "object";
    else if(className == *(uint32_t *)&PART) return "particle";
    else if(className == *(uint32_t *)&PCTL) return "particle_system";
    else if(className == *(uint32_t *)&PHYS) return "physics";
    else if(className == *(uint32_t *)&PLAC) return "placeholder";
    else if(className == *(uint32_t *)&PPHY) return "point_physics";
    else if(className == *(uint32_t *)&PROJ) return "projectile";
    else if(className == *(uint32_t *)&RAIN) return "weather";
    else if(className == *(uint32_t *)&SBSP) return "scenario_structure_bsp";
    else if(className == *(uint32_t *)&SCEN) return "scenery";
    else if(className == *(uint32_t *)&SCEX) return "shader_transparent_chicago_extended";
    else if(className == *(uint32_t *)&SCHI) return "shader_transparent_chicago";
    else if(className == *(uint32_t *)&SCNR) return "scenario";
    else if(className == *(uint32_t *)&SENV) return "shader_environment";
    else if(className == *(uint32_t *)&SGLA) return "shader_transparent_glass";
    else if(className == *(uint32_t *)&SHDR) return "shader";
    else if(className == *(uint32_t *)&SKY ) return "sky";
    else if(className == *(uint32_t *)&SMET) return "shader_transparent_meter";
    else if(className == *(uint32_t *)&SND) return "sound";
    else if(className == *(uint32_t *)&SNDE) return "sound_environment";
    else if(className == *(uint32_t *)&SOSO) return "shader_model";
    else if(className == *(uint32_t *)&SOTR) return "shader_transparent_generic";
    else if(className == *(uint32_t *)&SOUL) return "ui_widget_collection";
    else if(className == *(uint32_t *)&SPLA) return "shader_transparent_plasma";
    else if(className == *(uint32_t *)&SSCE) return "sound_scenery";
    else if(className == *(uint32_t *)&STR) return "string_list";
    else if(className == *(uint32_t *)&SWAT) return "shader_transparent_water";
    else if(className == *(uint32_t *)&TAGC) return "tag_collection";
    else if(className == *(uint32_t *)&TRAK) return "camera_track";
    else if(className == *(uint32_t *)&UDLG) return "dialogue";
    else if(className == *(uint32_t *)&UNHI) return "unit_hud_interface";
    else if(className == *(uint32_t *)&UNIT) return "unit";
    else if(className == *(uint32_t *)&USTR) return "unicode_string_list";
    else if(className == *(uint32_t *)&VCKY) return "virtual_keyboard";
    else if(className == *(uint32_t *)&VEHI) return "vehicle";
    else if(className == *(uint32_t *)&WEAP) return "weapon";
    else if(className == *(uint32_t *)&WIND) return "wind";
    else if(className == *(uint32_t *)&WPHI) return "weapon_hud_interface";
    else return "unknown";
}
